1:
	cat 1-create_database_if_missing.sql | sudo mysql -hlocalhost -uroot -proot
	cat 0-list_databases.sql | sudo mysql -hlocalhost -uroot -proot
	cat 1-create_database_if_missing.sql | sudo mysql -hlocalhost -uroot -proot
2:
	cat 0-list_databases.sql | sudo mysql -hlocalhost -uroot -proot
	cat 2-remove_database.sql | sudo mysql -hlocalhost -uroot -proot
	cat 0-list_databases.sql | sudo mysql -hlocalhost -uroot -proot
3:
	cat 3-list_tables.sql | sudo mysql -hlocalhost -uroot -proot mysql
4:
	cat 4-first_table.sql | sudo mysql -hlocalhost -uroot -proot hbtn_0c_0
	cat 3-list_tables.sql | sudo mysql -hlocalhost -uroot -proot hbtn_0c_0
5:
	cat 5-full_table.sql | sudo mysql -hlocalhost -uroot -proot hbtn_0c_0
6:
	cat 6-list_values.sql | sudo mysql -hlocalhost -uroot -proot hbtn_0c_0
7:
	cat 7-insert_value.sql | sudo mysql -hlocalhost -uroot -proot hbtn_0c_0
	cat 6-list_values.sql | sudo mysql -hlocalhost -uroot -proot hbtn_0c_0
	cat 7-insert_value.sql | sudo mysql -hlocalhost -uroot -proot hbtn_0c_0
	cat 7-insert_value.sql | sudo mysql -hlocalhost -uroot -proot hbtn_0c_0
	cat 6-list_values.sql | sudo mysql -hlocalhost -uroot -proot hbtn_0c_0
8:
	cat 8-count_89.sql | sudo mysql -hlocalhost -uroot -proot hbtn_0c_0 | tail -1
9:
	cat 9-full_creation.sql | sudo mysql -hlocalhost -uroot -proot hbtn_0c_0
10:
	cat 10-top_score.sql | sudo mysql -hlocalhost -uroot -proot hbtn_0c_0
11:
	cat 11-best_score.sql | sudo mysql -hlocalhost -uroot -proot hbtn_0c_0
12:
	cat 12-no_cheating.sql | sudo mysql -hlocalhost -uroot -proot hbtn_0c_0
	cat 10-top_score.sql | sudo mysql -hlocalhost -uroot -proot hbtn_0c_0
13:
	cat 13-change_class.sql | sudo mysql -hlocalhost -uroot -proot hbtn_0c_0
	cat 10-top_score.sql | sudo mysql -hlocalhost -uroot -proot hbtn_0c_0
14:
	cat 14-average.sql | sudo mysql -hlocalhost -uroot -proot hbtn_0c_0
15:
	cat 15-groups.sql | sudo mysql -hlocalhost -uroot -proot hbtn_0c_0
16:
	cat 16-no_link.sql | sudo mysql -hlocalhost -uroot -proot hbtn_0c_0
